-- Convert all TIMESTAMP columns to TIMESTAMPTZ for better consistency across services
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE wallets ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE wallets ALTER COLUMN verified_at TYPE TIMESTAMPTZ;

ALTER TABLE plans ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE subscriptions ALTER COLUMN started_at TYPE TIMESTAMPTZ;
ALTER TABLE subscriptions ALTER COLUMN expires_at TYPE TIMESTAMPTZ;
ALTER TABLE subscriptions ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE exchange_accounts ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE exchange_accounts ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE bots ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE bots ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE risk_settings ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE risk_settings ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE scanner_signals ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE order_intents ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE orders ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE orders ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE executions ALTER COLUMN executed_at TYPE TIMESTAMPTZ;
ALTER TABLE executions ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE wch_transactions ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE bot_logs ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE audit_logs ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE inbox_events ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE inbox_events ALTER COLUMN processed_at TYPE TIMESTAMPTZ;

ALTER TABLE outbox_events ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE outbox_events ALTER COLUMN last_attempt_at TYPE TIMESTAMPTZ;
ALTER TABLE outbox_events ALTER COLUMN next_retry_at TYPE TIMESTAMPTZ;
ALTER TABLE outbox_events ALTER COLUMN failed_at TYPE TIMESTAMPTZ;
